### ISSUE TITLE
規格的內容(如角度) font size 改為14px

### ISSUE THREAD

**Issue by wangejay** [wangejay/asiagolfshop#32]
![screenhunter_51 mar 24 23 13](https://cloud.githubusercontent.com/assets/4847028/6804961/86be79b2-d27b-11e4-8063-1a7df603dde9.jpg)

**Comment by tales00** [comment]
那個我應該已經改成 14px 了啊

**Comment by tales00** [comment]
的確有失誤，我修正了。
